[RFC] Be more cross-build friendly
osbuild/images pull request #1114
Opened 2024-12-20 11:37 UTC by mvo5

This PR tweaks the images library to work without "cgo" so that we can cross build. Thanks to @supakeen for raising this!

With the PR we can now do:
```
$ GOARCH=arm64 go build -o ibc-aarch64 -tags "containers_image_openpgp exclude_graphdriver_btrfs exclude_graphdriver_devicemapper" ./cmd/image-builder
```
in the image-builder-cli source tree.

2024-12-20 11:38 UTC, mvo5 commented on pkg/crypt/crypt_test.go
> +	cryptedPass, err := crypt("Hello world!", "$6$saltstring")
test vector is taken from the glibc source (e.g. https://github.com/lattera/glibc/blob/master/crypt/sha512c-test.c#L12)

2025-01-06 19:29 UTC, ondrejbudai commented
Food for thought: what if we used openssl everywhere? I suppose that less cgo is generally better.

2025-01-09 12:01 UTC, achilleas-k requested changes
LGTM, but unit tests in GH actions need openssl now.

Also a note about communicating external dependencies, which might be a topic for a follow-up PR.

2025-01-09 12:01 UTC, achilleas-k commented on .github/workflows/tests.yml
> +        run: CGO_ENABLED=0 go test -tags "containers_image_openpgp exclude_graphdriver_btrfs exclude_graphdriver_devicemapper exclude_graphdriver_overlay" ./...
Needs OpenSSL in the install step above.

2025-01-09 12:16 UTC, thozza commented
Rebased due to image build cache layout change (https://github.com/osbuild/images/pull/1130)

2025-01-09 15:25 UTC, supakeen commented on pkg/crypt/crypt_impl_non_cgo.go
> +	)
Generally such things do not exist (sadly) in language-package-formats. Go did/is growing support for `tools` which at least allows listing Go binaries that one depends on.

2025-01-09 15:35 UTC, mvo5 commented on .github/workflows/tests.yml
> +        run: CGO_ENABLED=0 go test -tags "containers_image_openpgp exclude_graphdriver_btrfs exclude_graphdriver_devicemapper exclude_graphdriver_overlay" ./...
Nice catch, thanks! This should be fixed now.

2025-01-09 15:43 UTC, mvo5 commented on pkg/crypt/crypt_impl_non_cgo.go
> +	)
I'm not aware of anything but it's also tricky to test upfront as in many situations (even if we would make this the default implementation) openssl would not be needed. I am a bit mad at linux that there is no standard commandline for this, only *openssl* and *mkpasswd* (which is part of whois?!?).

2025-01-10 06:03 UTC, supakeen commented on pkg/crypt/crypt_impl_non_cgo.go
> +	)
The Linux "standard commandline" is the kernel ABI (or I guess, libc?).

2025-01-10 06:04 UTC, supakeen approved these changes

2025-01-10 12:31 UTC, ondrejbudai commented
I actually have a quite strong opinion here: The more crypto we can offload to already existing implementation in operating systems, the better. I don't want our team to maintain needless crypto (and yes, since we are vendoring all the code, we are technically speaking maintaining it). Also, openssl and libxcrypt are widely used and recognized libraries.

2025-01-13 11:16 UTC, thozza approved these changes
LGTM.

The last commit has a typo in the commit message "kttp" vs. "http", but I can live with it :sweat_smile:

2025-01-13 15:20 UTC, mvo5 commented
> LGTM.
> 
> The last commit has a typo in the commit message "kttp" vs. "http", but I can live with it 😅

Nice catch! Indeed, the problematic import is `"github.com/ubccr/kerby/khttp"`, I fixed kttp to khttp now.

Sadly will need a re-view :)

2025-01-13 19:01 UTC, achilleas-k commented on pkg/crypt/crypt_impl_non_cgo.go
> +	)
Seems there's no real convention to work with here.  I'll resolve the thread here and we can pick it up elsewhere if we need to.

2025-01-13 19:02 UTC, achilleas-k approved these changes

2025-01-13 19:46 UTC, merged