Minimal raw xz
osbuild/images pull request #29
Opened 2023-07-14 11:39 UTC by sarmahaj

This pull request includes:

- minimal-raw image type support for rhel8/9 cs8/9
- fedora already had this image type , just added xz compression stage.
- xz compression brings down the image size from ~3.96GB to  ~700MB.
- updated README.md under image-types/ folder.
- osbuild-composer PR : https://github.com/osbuild/osbuild-composer/pull/3518

- [ ] adequate testing for the new functionality or fixed issue
- [ ] adequate documentation informing people about the change such as
  - [ ] submit a PR for the [guides](https://github.com/osbuild/guides) repository if this PR changed any behavior described there: https://www.osbuild.org/guides/

2023-07-18 10:09 UTC, achilleas-k requested changes
LGTM.  Thanks for bringing this over.

I'm marking this as "Request Changes" for now because I'd like to block it until #26 is merged to bring in build tests for all the image types.
Keep in mind that #26 removes the static manifests from `test/data/manifests/`, so you can drop them from this PR too to avoid conflicts.

2023-07-18 15:34 UTC, achilleas-k commented
I rebased on main and dropped the manifests.

2023-07-18 15:36 UTC, achilleas-k approved these changes

2023-07-18 19:39 UTC, merged

2023-07-19 10:14 UTC, sarmahaj commented
Thanks for the review and merge 👍