Report GitLab job failures globally
osbuild/images pull request #369
Opened 2024-01-15 18:17 UTC by achilleas-k

Never update the GitHub status at the end of a job.  Instead, let the
job retry and if another failure occurs, when everything is done, the
`fail` job will run in the `finish` stage and update the status
accordingly.

2024-01-15 19:22 UTC, achilleas-k commented
Forcing a failure in the generator pipeline to make sure failure reporting works as expected.

2024-01-16 01:34 UTC, bcl submitted a review, later dismissed
Looks good to me. Although the fact that the fail job has a green checkmark is ironic :)

2024-01-16 07:08 UTC, jrusz approved these changes
I thought it would run both `fail` and `finish` when the pipeline fails because it should have `when: always` by default, but apparently not, so LGTM :)

2024-01-16 07:11 UTC, jrusz commented
Also I suppose that if you want the `fail` job to really fail, you can add another line to the `script` section with `exit 1` that will make it actually fail and stop there

2024-01-16 07:20 UTC, jrusz requested changes
I actually think that you should add the `exit 1` after running the `update_githu_status.sh` script. The green fail can be confusing.

2024-01-16 11:52 UTC, achilleas-k commented
> I actually think that you should add the `exit 1` after running the `update_githu_status.sh` script. The green fail can be confusing.

I had the same thought when Brian commented so good, on it!

2024-01-16 12:21 UTC, jrusz approved these changes

2024-01-16 15:29 UTC, merged