Fedora: Update package sets for upstream changes
osbuild/images pull request #480
Opened 2024-02-27 18:20 UTC by paulwhalen

In Fedora 40+ `passwd` is now provided by `shadow-utils`  ( https://bodhi.fedoraproject.org/updates/FEDORA-2024-e07b775e4e )

`podman-plugins` is no longer included in the new release of [Podman 5](https://src.fedoraproject.org/rpms/podman/c/2ab1bb3d2d6b3e9df18449494a081fcbe8044d4c?branch=rawhide) (F40+ as well) .

This PR updates the affected package-sets.

2024-02-27 19:10 UTC, djach7 approved these changes
LGTM, reviewed for English conventions with average GO knowledge.

2024-02-28 07:19 UTC, supakeen submitted a review, later dismissed

2024-02-28 07:20 UTC, supakeen commented
@paulwhalen This needs only linter fixes.

2024-02-28 07:22 UTC, supakeen commented on pkg/distro/fedora/package_sets.go
> +	}
This could be an `else` :)

2024-02-28 19:21 UTC, achilleas-k reviewed
LGTM but requires merge conflict resolution

2024-02-28 19:21 UTC, achilleas-k requested changes
LGTM but requires merge conflict resolution

2024-02-28 19:23 UTC, achilleas-k commented
The osbuild-composer integration tests aren't required for merging.  They fail when changes are needed to integrate osbuild/images into osbuild-composer.

2024-02-28 20:43 UTC, supakeen approved these changes

2024-02-28 20:57 UTC, achilleas-k approved these changes

2024-02-28 21:40 UTC, merged