dnfjson: allow (optional) field `solver` in the dnfjson output
osbuild/images pull request #723
Opened 2024-06-03 09:26 UTC by mvo5

With the new "dnf5" solver is seems useful to allow the dnfjson code return what solver was actually used in the transaction.

This commit allows an (optional) "solver" field in the json that is returned from the dnfjson helper. It does not do more yet but we should (probably) make it avaialble for the higher layers too so that it can be e.g. logged.

See also https://github.com/osbuild/osbuild/pull/1776

2024-06-03 19:02 UTC, bcl commented
Looks good, other than the linting complaints :)

2024-06-04 09:49 UTC, achilleas-k requested changes

2024-06-04 12:36 UTC, achilleas-k approved these changes
LGTM.  Technically we can merge this before the osbuild PR and it wouldn't be a problem, but let's do it in proper order.

Then we could also run the unit tests in `dnfjson_test.go` against both solvers.

2024-06-04 23:11 UTC, bcl approved these changes
Looks good, pylint is apparently befuddled by having a raise in an else before using a variable.

2024-06-04 23:18 UTC, bcl commented
Made #729 to ignore the pylint error

2024-08-01 09:50 UTC, thozza approved these changes

2024-08-01 10:25 UTC, merged